[package]
name = "mork_ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
mork-frontend = { path = "../../MORK/frontend" }
mork-expr = { path = "../../MORK/expr" }
mork = { path = "../../MORK/kernel" }

[lib]
name = "mork_ffi"
crate-type = ["cdylib"]
